### PR TITLE
Pytorch fixes

### PR DESCRIPTION
**Pull request by emanjavacas**
This makes the model more similar to the keras implementation. It also adds initalization schemes to the pytorch branch, which were missing. Results on the geste corpus seem to be consistently similar between branches.

### CODE REVIEW

**Comment by emanjavacas** [comment]
There are quite some improvements in this PR.
- Previously there was a disagreement with the keras branch, which resulted on lower performance in pytorch. After the change performance seems to be about the same level.
- Attention is now much faster during training because it runs the whole sequence at once instead of step by step.
- There are some options in the pytorch model that are not available in keras (three different ways of pooling a 3D tensor `(seq_len x batch x input_size)` into a 2D tensor `(batch x output_size)`). In keras this is done by a linear transformation from `(seq_len * input_size)` onto `(output_size)`. In pytorch this option is implemented as `flatten` in the new `BottleEncoder` class, which is use in two cases. There are two other options in pytorch that are `max` and `rnn` which do maxpooling over the sequence length dimension or run a bidirectional rnn and returns the last summary vector.
- I've added implementations of initialization schemes, which were absent.
- For the bidirectional rnns, the pytorch branch allows you to choose from either summing across both hidden sizes or concatenating both directions in a (precomputed) hidden size of half the original. In my experience the second variant works better and is faster (given the reduction in hidden size in the rnn). The option is called 'merge_mode' and takes either `concat` or `sum` as arguments.
- There is also a WIP implementation of beam search. For some reason, it is now always outputing `+++++...`, so I will have to debug a bit more.
- Lastly, the pytorch branch allows you now to run the lemma generation subnetwork with a convolutional encoder as long as your `nb_filters` is equal to `nb_dense_dims` (which isn't a weird situation). I've implemented this since POS-tagging on the recurrent encoding of the target doesn't seem to work very well (my impression is that the input sequences are perhaps too short), but the convolutional encoding does perform pretty well. Since the convolutions also output a sequence with proper sequential meaning, that can be attended to, this scheme also makes sense.

**Comment by emanjavacas** [comment]
Found out the reason for the issue with beam search. Currently the tagger expects the full distribution over the vocabulary at each step to take the argmax over the sequence. This means it is already implementing argmax decoding. For beam search to work, tagger should expect the already decoded output and not the full distribution. This means basically remove argmax decoding from tagger https://github.com/hipster-philology/pandora/blob/master/pandora/preprocessing.py#L591 and instead just expect the already decoded output for the lemma.
I'd move all the decoding logic inside the model (not just for the lemmas when generated), since implementing more complex decoding methods like beam search is hard to abstract because they need to interact with the model during decoding. PR's welcome.

**Comment by PonteIneptique** [comment]
@emanjavacas Can you check the conflicting pytorch model before I review ?

**Review by PonteIneptique — APPROVED** [review]
Generally okay with the PR but need to fix conflict

**Pull request merged**
