### PR TITLE
Updated requirements and added col_pos and col_lemma config options.

### PR DESCRIPTION
**Pull request by peterdekker**
I added configparser to the requirements.

I added col_pos and col_lemma to the possible options in the config file. With the col_pos and col_lemma config options, the user can set which column from the input file should be read as POS tag and which as lemma. If the options are omitted, it defaults to col_pos=2 and col_lemma=1.

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Hey,
Many thanks for your pull request. If you add `col_pos` and `col_lemma`, you should probably add a `col_morph` as well (with default to 3).

**Comment by PonteIneptique** [comment]
There is also a conflict with the latest merge :) Sorry !

**Comment by peterdekker** [comment]
Thanks for your comments! I merged with the main repository and added the col_morph argument. 

Unfortunately, Travic CI shows there is an error when using the PyTorch backend. This error only occurs with the current PyTorch version on pip, not with my local PyTorch version. It should be fixed by using the latest PyTorch source code: https://github.com/pytorch/pytorch/issues/4380

**Comment by peterdekker** [comment]
@PonteIneptique @Jean-Baptiste-Camps Do you think my pull request could be merged?

**Comment by PonteIneptique** [comment]
Hey @pdekker12 !
I'll test it locally next Monday, I am truly sorry for not taking care of this earlier.

**Comment by peterdekker** [comment]
Thanks, no problem!

**Review by PonteIneptique — APPROVED** [review]

**Comment by PonteIneptique** [comment]
Thanks !

**Pull request merged**
