### PR TITLE
Updated main cli files name for clarity (Fixed #52)

### LINKED ISSUE #52: main.py, unseen.py, train.py
@mikekestemont : This is a result from the merge operation that should be settled: I'm
guessing main.py should become obsolete.

### PR DESCRIPTION
**Pull request by PonteIneptique**

### CODE REVIEW

**Comment by mikekestemont** [comment]
cool, thx.

**Comment by emanjavacas** [comment]
Should I merge this?

**Comment by mikekestemont** [comment]
+1

**Comment by PonteIneptique** [comment]
Yup

Le 4 oct. 2017 10:40 AM, "Mike Kestemont" <notifications@github.com> a
écrit :

> +1
>
> On Wed, Oct 4, 2017 at 10:37 AM, Enrique Manjavacas <

**Comment by mikekestemont** [comment]
I am guessing this fails because of naming conflicts so I'll merge anyway...

**Pull request merged**
