### PR TITLE
check whether input data was loaded

### LINKED ISSUE #65: Train.py not working anymore : self.max_token_len = len(max(tokens, key=len)) + 1
From #55

### PR DESCRIPTION
**Pull request by PonteIneptique**
Fix #65

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I approve but I need someone else to approve because I had to open the PR :D

**Comment by PonteIneptique** [comment]
(btw : just do a squash and merge ;) )

**Comment by emanjavacas** [comment]
I can't either. Maybe we should ask Linus Torvalds to do the merge himself.

**Comment by PonteIneptique** [comment]
You just need to approve the review
The new system blocks us to merge our own PR for good reason. Here our good friend @mikekestemont just PRed the wrong repo :P

**Review by mikekestemont — APPROVED** [review]
LGTM

**Pull request merged**
