### PR TITLE
Categorization

### LINKED ISSUE #67: Training with include_morph = label yiels TypeError: to_categorical() got an unexpected keyword argument 'nb_classes'
This is similar to the bug described in #12 . When I launch training on the Geste sample data, with
````python
include_morph = label
````
in the config, I get the following error,
````
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    cli_train()
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 144, in cli_train
    train_func(**vars(parser.parse_args()))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 94, in train_func
    tagger.setup_to_train(**data_sets)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/tagger.py", line 230, in setup_to_train
    morph=self.train_morph)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/preprocessing.py", line 516, in transform
    X_morph, nb_classes=len(self.morph_encoder.classes_))
TypeError: to_categorical() got an unexpected keyword argument 'nb_classes
````

This does not happen, though, with
````python
include_morph = multilabel
````
which seems to work quite fine (I'm actually impressed by the results obtained with this option).

### PR DESCRIPTION
**Pull request by mikekestemont**
This closes #67

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Ok, this solves the first bug, but it leads to another one:
````
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    cli_train()
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 154, in cli_train
    train_func(**vars(parser.parse_args()))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 104, in train_func
    tagger.setup_to_train(**data_sets)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/tagger.py", line 230, in setup_to_train
    morph=self.train_morph)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/preprocessing.py", line 516, in transform
    X_morph, num_classes=len(self.morph_encoder.classes_))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/utils.py", line 353, in to_categorical
    y = np.array(y, dtype='int').ravel()
ValueError: invalid literal for int() with base 10: 'NOMB._p|GENRE_f|CAS_r'
````

**Comment by mikekestemont** [comment]
is this for multilabel?

**Comment by Jean-Baptiste-Camps** [comment]
No, for single label. multilabel still works fine, it has not changed.

**Comment by PonteIneptique** [comment]
I think, given the fact it was for one bug, we can close this PR and see for the future the resolution of the second :)

**Review by PonteIneptique — APPROVED** [review]

**Pull request merged**
