### PR TITLE
Fix travis segumentation fault

### LINKED ISSUE #103: Segmentation fault on travis
Current build fails to build.
Most likely due to the fact that Pandora is trying to use 10 workers on a 2 or 3 threads (can't remember exactly) enabled machine. Will look into it

### PR DESCRIPTION
**Pull request by PonteIneptique**
Fix #103 
Also cleans the way we open file by making a with statement and avoid as such "file left open" warnings.

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Hey, @PonteIneptique , should not we fix and merge this PR as well ? Any idea on the source of the failed Travis test ?

**Comment by PonteIneptique** [comment]
There was a pip install that failed. I just launched a rebuild to check the situation.

**Comment by PonteIneptique** [comment]
Here ya go ;)

**Review by Jean-Baptiste-Camps — APPROVED** [review]
Ok, let's go then.

**Pull request merged**
