### PR TITLE
Pytorch

### PR DESCRIPTION
**Pull request by emanjavacas**
Most important changes for the master branch is that all model implementation has been moved to pandora/impl. Each model implements an interface defined in pandora/impl/base_model.py.

### CODE REVIEW

**Comment by emanjavacas** [comment]
Any volunteers to review?

**Comment by PonteIneptique** [comment]
Well, right now, it's unmergeable :)

But I'll launch a train later tonight on the Medieval French corpora

**Comment by PonteIneptique** [comment]
On top of that, I think before the merge conflict have been taken care of, it might be dangerous to do a definitive review, given that merging conflict could screw the code base

**Comment by PonteIneptique** [comment]
Other issue : we need requirements*.txt and setup,*.py updated

**Comment by emanjavacas** [comment]
Hi. I have the feeling that we are not on the same page. I was already expecting merge conflicts since the keras model moved from being the only model to being just an implementation of the interface. However, I'd expect that most conflicts are only at that level, and in general it shouldn't be too hard to actual fix the conflicts, especially if all the tagger-model interaction have stayed the same, which seems to be the case. Are there any other particular reasons that I am not aware of for this being "unmergeable" apart from the merge conflicts?

I am **NOT** going to be too stubborn on having to merge right now, but it is true that the more we wait the harder it all becomes...

**Comment by emanjavacas** [comment]
About the requirements.txt, I agree they have to be updated. However, I'd keep tensorflow/keras and pytorch outside requirements.txt since they are very platform dependent. It's true that ocasionally these libraries can be pipped, but in my experience most of the time, it doesn't work/it's not what the user wants (since you still have to check against your cuda and your python version).

**Comment by PonteIneptique** [comment]
Wait, you took badly something I said : it's "unmergeable" as it cannot be merged due to merge conflict...
What I meant is just : can the merge conflict be fixed before we review this ?

On top of this, I still think pipable is a good thing to do, at least to keep track of the version to install...

**Comment by emanjavacas** [comment]
Hi,sorry I just realized I forgot a "not" in my previous comment (see edit) and hence my message might've come across a bit too harsh. Would you suggest that I go and try to fix first all the issues? I'd do it but usually it's recommended that someone unrelated to the PR does it, right? I can take care of it if you want.

**Comment by emanjavacas** [comment]
I've resolved the conflicts (I wasn't sure in some cases, since some of the code in this PR was written by mike). I've followed the pytorch branch most of the cases except in those involving the cli (main.py and unseen.py), since the cli seems to have overseeded the previous script-approach.
It might be that I've undone some of the work that was done recently, but I hope we can figure it out during review.

**Comment by emanjavacas** [comment]
RE: requirements. Can't we just add to the tensorflow/pytorch versions to the Readme with some little explanation where to go to install them? At least for pytorch it wouldn't really make sense to stick to pip, since it will work in even less cases than tensorflow.

**Comment by emanjavacas** [comment]
Let's move the pip discussio over to #5

**Comment by PonteIneptique** [comment]
At least the version in the readme would be fine.

**Comment by PonteIneptique** [comment]
Looking at the code : could you add a pytorch CLI argument ?

**Comment by emanjavacas** [comment]
Sure, doo you mean in cli.py?

**Comment by PonteIneptique** [comment]
Exactly. Something like --pytorch to switch to pytorch or --backend pytorch (Which would allow to switch default later ;) )

**Comment by emanjavacas** [comment]
I am not so sure about how cli.py works in master, but so far I've been using "model = PyTorch" in the config file. Maybe we can deal with this once we have the merge done?

**Comment by PonteIneptique** [comment]
I usually try to get a feature completely adapted before merging, but this is only how I do. Let me see if I can do something about this issue.
On the other hand, maybe @mikekestemont just needs to give the approval or not, and we can move slowly up to fixed status on master.

**Comment by PonteIneptique** [comment]
Actually, the way you had the merge completely removed the use of logger class...
I'd say we squash and check the diff for this one...

**Comment by emanjavacas** [comment]
Sure, the only thing is that I am suppose to add functionality to a branch without knowing exactly how it works in the target branch. It'd be much easier for me to work on this after the merge, once I get familiarized with the new stuff.

**Comment by PonteIneptique** [comment]
Let's merge then.
The functionality that was added was part of this one : 

https://github.com/hipster-philology/pandora/blob/ed900b4bcc64d706396cefcf6d5d2a00c13d6e88/pandora/tagger.py#L561-L567

**Comment by PonteIneptique** [comment]
If I do squash and merge, we have a nice history. But we lose your name. I'd say go ahead and do a squash

**Review by PonteIneptique — APPROVED** [review]

**Comment by emanjavacas** [comment]
Is it just those lines that I have to add back? I am not sure what you have in mind, but the commit you referenced ed900b4 is not about the logger but about plotting.

**Comment by PonteIneptique** [comment]
I added a link to the pr in an issue for this specific thing.

Le 1 oct. 2017 7:45 PM, "Enrique Manjavacas" <notifications@github.com> a
écrit :

Merged #45 <https://github.com/hipster-philology/pandora/pull/45>.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/hipster-philology/pandora/pull/45#event-1273147074>,
or mute
the thread

**Pull request merged**
