### PR TITLE
Issue 74

### PR DESCRIPTION
**Pull request by PonteIneptique**
You need to install jsonpickle on top of what you have (version shown in requirements)
I could not test it but this should make things work...
I took the time to sanitize a little the class :)

### CODE REVIEW

**Comment by PonteIneptique** [comment]
You'll need to retrain.
You should probably do one epoch only for the tests ;)

**Comment by Jean-Baptiste-Camps** [comment]
No, I prefer to test on 42 epochs, because it makes for better testing.

**Comment by PonteIneptique** [comment]
you-think-you-amp-039-re-funny_o_1354547

**Comment by Jean-Baptiste-Camps** [comment]
Help, someone is resorting to a meme.

**Comment by Jean-Baptiste-Camps** [comment]
With label:
````
Traceback (most recent call last):
  File "tagger.py", line 6, in <module>
    cli_tagger()
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 255, in cli_tagger
    tag_dir(**vars(args))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 186, in tag_dir
    annotations = tagger.annotate(unseen_tokens)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/tagger.py", line 702, in annotate
    predictions=preds['morph_out'])
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/preprocessing.py", line 644, in inverse_transform_morph
    return self.morph_encoder.inverse_transform(predictions)
AttributeError: 'NoneType' object has no attribute 'inverse_transform'
````
With multilabel:
````
Traceback (most recent call last):
  File "tagger.py", line 6, in <module>
    cli_tagger()
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 253, in cli_tagger
    tag_string(**vars(args))
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/cli.py", line 213, in tag_string
    annotations = tagger.annotate(unseen_tokens)
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/tagger.py", line 702, in annotate
    predictions=preds['morph_out'])
  File "/home/jbc/Data/F/pandora/pandora_testing/hipster-philology/pandora/pandora/preprocessing.py", line 649, in inverse_transform_morph
    for label, idxs in self.morph_idxs.items():
AttributeError: 'NoneType' object has no attribute 'items'
````

**Comment by PonteIneptique** [comment]
Just to be sure : after having trained a new time ? (sorry for asking)

**Comment by PonteIneptique** [comment]
I'm stupid...

**Comment by PonteIneptique** [comment]
Just try to reload, you should not need to retrain with this change.

**Review by Jean-Baptiste-Camps — APPROVED** [review]
Works now, thanks !

**Pull request merged**
